name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # This step checks out the repository

      - name: Set up Git
        run: |
          git config --global user.name 'Your GitHub Username'
          git config --global user.email 'your-email@example.com'

      - name: Update README
        run: |
          git add README.md
          git commit -m "Update README with private contributions" || echo "No changes to commit"
          git push
