name: Update README with GitHub Stats

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Update README with private contributions" || echo "No changes to commit"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Bumbi-dev/Bumbi-dev.git


